NUM_WORKERS: 0
BATCH_SIZE: 8
NUM_EPOCHS: 25
LEARNING_RATE: 0.0001
WEIGHT_DECAY: 0.0001
MOMENTUM: 0.9
DROPOUT_RATE: 0.5
EARLY_STOPPING_PATIENCE: 10
AVERAGE: "macro"
PRINT_EVERY: 1
SAVE_PATH: "artifacts/densenet121"
SAVE_MODEL: false
SAVE_METRICS: false
SAVE_PATIENCE: 10
SHUFFLE: True
