PREPROCESSING:
  ROTATION_RANGE: 45
  WIDTH_SHIFT_RANGE: 0.1
  HEIGHT_SHIFT_RANGE: 0.1
  SHEAR_RANGE: 0.1
  ZOOM_RANGE: 0.2
  HORIZONTAL_FLIP: true
  VERTICAL_FLIP: true
  BRIGHTNESS_RANGE: [0.4, 0.9]
  CHANNEL_SHIFT_RANGE: 150.0
  FILL_MODE: "nearest"
  DROP_OUT: true