NUM_WORKERS: 0
BATCH_SIZE: 32
NUM_EPOCHS: 10
LEARNING_RATE: 0.0001
WEIGHT_DECAY: 0.0001
MOMENTUM: 0.9
DROPOUT_RATE: 0.5
EARLY_STOPPING_PATIENCE: 10
AVERAGE: "macro"
PRINT_EVERY: 100
SAVE_PATH: "artifacts/effcapsnet"
SAVE_MODEL: true
SAVE_METRICS: True
SAVE_PATIENCE: 10
SHUFFLE: false
