NUM_WORKERS: 0
BATCH_SIZE: 4
NUM_EPOCHS: 10
LEARNING_RATE: 0.001
WEIGHT_DECAY: 0.0001
MOMENTUM: 0.9
DROPOUT_RATE: 0.5
EARLY_STOPPING_PATIENCE: 10
AVERAGE: "macro"
PRINT_EVERY: 10
SAVE_PATH: "artifacts/effcapsnet"
SAVE_MODEL: True
SAVE_METRICS: True
SAVE_PATIENCE: 10
